version: '3'
services:
  arangodb:
    image: arangodb:latest
    ports:
      - 8529:8529
    volumes:
      - ./volumes/arangodb/data:/var/lib/arangodb3
      - ./volumes/arangodb/apps:/var/lib/arangodb3-apps
    environment:
      ARANGO_ROOT_PASSWORD: rootpassword

  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - 2181:2181

  kafka:
    depends_on:
      - zookeeper
    image: wurstmeister/kafka
    ports:
      - 9092:9092
    volumes:
      - ./volumes/kafka:/kafka
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181