### NOTE: To use this file VSC REST Client extension must be installed 

### Gets a Tenant by id
GET http://localhost:5000/tenants/<tenantId>

### Creates a Tenant
POST http://localhost:5000/tenants
Content-Type: application/json

{
    "name": "name"
}